# 베이스 이미지
FROM spark:4.0.0-preview2-scala2.13-java21-ubuntu

# 루트 권한으로 변경
USER root

# Python 설치 (루트 권한으로 실행)
RUN set -ex; \
    apt-get update; \
    apt-get install -y python3 python3-pip; \
    rm -rf /var/lib/apt/lists/*

# 원래 사용자로 돌아감 (필요한 경우, 사용자명 변경)
USER spark

# 필요한 스크립트를 복사
COPY log_processing.py /opt/spark/scripts/log_processing.py
