apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/log-server/log.log

    output.logstash:
      hosts: ['logstash-service:5044']

    setup.kibana:
      host: "kibana-service:5601"
