apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model
  namespace: kserve
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://ai-bucket/saved_model.joblib
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
