apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "PlayerID: %{NUMBER:playerId}, ActionType: %{WORD:actionType}, Timestamp: %{NUMBER:timestamp}" }
      }
    }

    filter {
      mutate {
        remove_field => ["@version", "host", "agent", "ecs", "tags", "log", "input"]
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "logs"
      }
    }
