apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: api-port           # API 포트의 이름
      protocol: TCP
      port: 9000               # API 포트
      targetPort: 9000
      nodePort: 30000          # 외부에서 접근할 포트 (9000번 API)
    - name: web-ui-port         # 웹 UI 포트의 이름
      protocol: TCP
      port: 9090               # 웹 UI 포트
      targetPort: 9090
      nodePort: 30001          # 외부에서 접근할 포트 (9090번 웹 UI)
  type: NodePort
