apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  template:
    spec:
      containers:
        - name: model-training
          image: vamlin/model_training:latest
          command: ["python", "model_training.py"]
      restartPolicy: Never
